[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "numpy>=2.3.0",
    "pandas>=2.3.0",
    "saspy>=5.103.0",
    "scikit-learn>=1.7.0",
]
